services:
  devops:
    container_name: devops
    image: ghcr.io/clouddrove/devops-machine:v4-arm64
    mem_limit: 3g
    memswap_limit: 3g
    cpu_shares: 30
    privileged: true
    ports:
      - "1310:22" # ssh
    volumes:
      - ./bin/devops:/image/
      - ~/Workspace/data/log:/var/log/
      - ./bin/devops/etc/zshrc:/home/ubuntu/.zshrc
      - ./bin/devops/etc/zsh/aliases.conf:/home/ubuntu/.aliases
      - ./bin/devops/etc/zsh/extra.conf:/home/ubuntu/.extra
      - ~/Workspace:/home/ubuntu/workspace
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.aws:/home/ubuntu/.aws
      - ~/.zsh_history:/home/ubuntu/.zsh_history
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - ~/.kube:/home/ubuntu/.kube
      - ~/.azure:/home/ubuntu/.azure 
      - ~/.config/gcloud:/home/ubuntu/.config/gcloud  
    networks:
      dev_net_devops:
        ipv4_address: 10.13.0.13
    command: >
      sh -c "chown -R ubuntu:ubuntu /home/ubuntu/ &&
             service ssh start &&
             su ubuntu -c 'tail -f /dev/null'"

networks:
  dev_net_devops:
    driver: bridge
    ipam:
     config:
       - subnet: 10.13.0.0/16
         gateway: 10.13.0.1
