name: Docker Workflow
# This permission are helpful for pushing vulnerability in security tab
permissions:
  actions: read
  contents: read
  security-events: write
  statuses: write

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  docker-scanner:
    uses: clouddrove/github-shared-workflows/.github/workflows/docker-scanner.yml@1.2.7
    with:
      severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
      dockerfile-path: "./.docker/."
      security-upload: "true"