name: Enigma Docker Build and Publish.

on:
  push:
    branches:
      - feat/enigma
  workflow_dispatch:

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      DOCKER_IMAGE: devops-machine
      REPO: ${{ github.repository }}
      DOCKER_TAG: ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
      # DOCKER_TAG: ghcr.io/clouddrove/devops-machine:v2
      PROVIDER: github
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Build Docker Image
        uses: clouddrove/enigma@v0.0.7
        with:
          command: bake
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          DOCKERFILE_PATH: .docker/Dockerfile
          GITHUB_USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB }}
  
      - name: Publish Docker Image
        uses: clouddrove/enigma@v0.0.7
        with:
          command: publish
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          DOCKERFILE_PATH: .docker/Dockerfile
          GITHUB_USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB }}
   
      # - name: Upload SARIF result
      #   id: upload-sarif
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: sarif.output.json
