name: Enigma Docker Build and Publish.
on:
  push:
    tags: [ v* ]

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      DOCKER_IMAGE: devops-machine
      DOCKER_TAG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      PROVIDER: github
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Build Docker Image
        uses: clouddrove/enigma@v0.0.8
        with:
          command: bake
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          DOCKERFILE_PATH: .docker/Dockerfile
          GITHUB_USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB }}
          BUILD_ARCHITECTURE: amd64, arm64
  
      - name: Publish Docker Image
        uses: clouddrove/enigma@v0.0.7
        with:
          command: publish
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          DOCKERFILE_PATH: .docker/Dockerfile
          GITHUB_USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB }}
